# Generated by Django 3.1.1 on 2020-09-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetModel',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tweet', models.CharField(max_length=200)),
            ],
        ),
    ]
